const logo = document.querySelector('.navbar-logo')
const button = document.querySelector('.button')
const header = document.querySelector('.header')
const image = document.querySelector('.hello-image')
const wave = document.querySelector('.svg')

const tl = new TimelineMax({delay: 0})
tl.fromTo(logo, 0.7, {x: '100', opacity: 0}, {x: '0', opacity: 1})
.fromTo(button, 0.7, {x: '100', opacity: 0}, {x: '0', opacity: 1})
.fromTo(header, 0.7, {x: '100', opacity: 0}, {x: '0', opacity: 1})
.fromTo(image, 1.2, {opacity: 0}, {opacity: 1})
.fromTo(wave, 1.2, {opacity: 0}, {opacity: 1})